# Generated by Django 4.2.3 on 2023-07-21 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('battles', '0018_battle_anarchy_points_battle_anarchy_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunny_video_id', models.CharField(max_length=255)),
                ('battle_start_time', models.DateTimeField()),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('uploader',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
