# Generated by Django 4.2.3 on 2023-07-21 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0018_battle_anarchy_points_battle_anarchy_rank_and_more'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlevideo',
            name='battle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='battles.battle'),
        ),
    ]
