# Generated by Django 4.2 on 2023-04-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures',
                                    verbose_name='profile picture'),
        ),
    ]
