# Generated by Django 4.2 on 2023-04-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sponsor_public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('key',
                 models.CharField(default=users.models.generate_key, max_length=40, primary_key=True, serialize=False,
                                  unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
