# Generated by Django 4.2 on 2023-04-13 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_is_sponsor_public_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
