# Generated by Django 4.2.1 on 2023-05-04 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import splatnet_assets.fields


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_apikey_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_splashcat_sponsor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sponsor_public',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_favorite_color',
            field=splatnet_assets.fields.ColorField(default='00000000', max_length=8),
        ),
        migrations.CreateModel(
            name='GitHubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(unique=True)),
                ('is_sponsor', models.BooleanField(default=False)),
                ('is_sponsor_public', models.BooleanField(default=False)),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='github_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
