# Generated by Django 4.2.1 on 2023-05-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_remove_user_is_splashcat_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githublink',
            options={'verbose_name': 'GitHub Link'},
        ),
        migrations.AddField(
            model_name='githublink',
            name='sponsorship_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
