# Generated by Django 4.2.1 on 2023-05-05 13:33

from django.db import migrations, models

import splatnet_assets.fields


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=30, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_favorite_color',
            field=splatnet_assets.fields.ColorField(default='000000ff', max_length=8),
        ),
    ]
