# Generated by Django 4.2.1 on 2023-05-05 17:23

from django.db import migrations

import splatnet_assets.fields


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_alter_user_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_favorite_color',
            field=splatnet_assets.fields.ColorField(default='9333eaff', max_length=8),
        ),
    ]
