# Generated by Django 4.2.1 on 2023-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_alter_user_saved_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='githublink',
            name='github_username',
            field=models.CharField(default='', max_length=39),
            preserve_default=False,
        ),
    ]
