# Generated by Django 4.2.1 on 2023-05-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_githublink_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=False, verbose_name='verified email'),
        ),
    ]
