# Generated by Django 4.2.1 on 2023-05-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_user_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
