# Generated by Django 4.2.1 on 2023-05-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_export_pending',
            field=models.BooleanField(default=False, verbose_name='data export pending'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_data_export',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last data export'),
        ),
    ]
