# Generated by Django 4.2.1 on 2023-06-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_user_data_export_pending_user_last_data_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='x_battle_division',
            field=models.CharField(
                choices=[('UNSPECIFIED', 'Unspecified'), ('TENTATEK', 'Tentatek'), ('TAKOROKA', 'Takoroka')],
                default='UNSPECIFIED', max_length=20, verbose_name='X Battle division'),
        ),
    ]
