# Generated by Django 4.2.2 on 2023-07-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0016_user_x_battle_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_pronouns',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='preferred pronouns'),
        ),
    ]
