# Generated by Django 4.2.3 on 2023-07-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_user_preferred_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_to_upload_videos',
            field=models.BooleanField(default=False, verbose_name='approved to upload videos'),
        ),
        migrations.AddField(
            model_name='user',
            name='video_collection_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='video collection id'),
        ),
    ]
