# Generated by Django 4.2.3 on 2023-09-10 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0018_user_approved_to_upload_videos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_rel_me_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
