# Generated by Django 4.2.4 on 2023-11-12 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0019_profileurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileurl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_urls',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
