# Generated by Django 5.0.2 on 2024-02-27 01:08

import django_choices_field.fields
import splatnet_assets.common_model_choices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profileurl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='x_battle_division',
            field=django_choices_field.fields.TextChoicesField(choices=[('UNSPECIFIED', 'Unspecified'), ('TENTATEK', 'Tentatek'), ('TAKOROKA', 'Takoroka')], choices_enum=splatnet_assets.common_model_choices.XBattleDivisions, default='UNSPECIFIED', max_length=11, verbose_name='X Battle division'),
        ),
    ]
