# Generated by Django 5.0.6 on 2024-06-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_coral_friend_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_cover',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers', verbose_name='profile cover'),
        ),
    ]
