# Generated by Django 5.0.7 on 2024-07-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_page_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_entitlements',
            field=models.JSONField(default=[], verbose_name='stripe entitlements'),
        ),
    ]
