# Generated by Django 5.0.7 on 2024-07-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_stripe_entitlements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_entitlements',
            field=models.JSONField(default=list, verbose_name='stripe entitlements'),
        ),
    ]
