# Generated by Django 5.0.7 on 2024-07-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_stripe_entitlements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_entitlements',
            new_name='_stripe_entitlements',
        ),
    ]
