# Generated by Django 5.1.1 on 2024-09-25 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_stripe_entitlements_user__stripe_entitlements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_stripe_entitlements',
            field=models.JSONField(blank=True, default=list, verbose_name='stripe entitlements'),
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_on', models.DateTimeField(auto_now_add=True, verbose_name='followed on')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='followed')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='follower')),
            ],
            options={
                'verbose_name': 'Follower',
                'verbose_name_plural': 'Followers',
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
