# Generated by Django 5.2.5 on 2025-08-22 17:31

import django_choices_field.fields
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_stripe_entitlements_user__stripe_entitlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_player_names',
            field=django_choices_field.fields.TextChoicesField(choices=[('ALWAYS', 'Always'), ('PRIVATE_BATTLES', 'Only in private battles'), ('PUBLIC_BATTLES', 'Only in public battles')], choices_enum=users.models.PlayerNameShown, default='ALWAYS', max_length=15, verbose_name='show player names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='_stripe_entitlements',
            field=models.JSONField(blank=True, default=list, verbose_name='stripe entitlements'),
        ),
    ]
