# Generated by Django 5.1.1 on 2024-09-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user__stripe_entitlements_follower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
    ]
