# Generated by Django 5.1.1 on 2024-09-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipeint',
            new_name='recipient',
        ),
    ]
