# Generated by Django 5.1.1 on 2024-09-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_rename_recipeint_notification_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
