# Generated by Django 5.1.1 on 2024-09-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_created_on_notification_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
