# Generated by Django 5.1.1 on 2024-09-30 00:33

import django.contrib.auth.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[users.models.validate_no_profanity], verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=30, validators=[users.models.validate_no_profanity], verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_pronouns',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.models.validate_no_profanity], verbose_name='preferred pronouns'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.models.validate_no_profanity], verbose_name='username'),
        ),
    ]
