# Generated by Django 4.2 on 2023-04-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('favored_ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                                      to='splatnet_assets.ability')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='splatnet_assets/')),
                ('type', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=100)),
                ('original_file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizationString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('type', models.CharField(
                    choices=[('OTHER', 'Other'), ('WEAPON_NAME', 'Weapon Name'), ('SUB_WEAPON_NAME', 'Sub Weapon Name'),
                             ('SPECIAL_WEAPON_NAME', 'Special Weapon Name'), ('TITLE_ADJECTIVE', 'Title Adjective'),
                             ('TITLE_SUBJECT', 'Title Subject'), ('HEAD_GEAR', 'Head Gear'),
                             ('CLOTHING_GEAR', 'Clothing Gear'), ('SHOES_GEAR', 'Shoes Gear'), ('ABILITY', 'Ability'),
                             ('STAGE', 'Stage')], max_length=50)),
                ('string_de_de', models.TextField(blank=True)),
                ('string_en_gb', models.TextField(blank=True)),
                ('string_en_us', models.TextField(blank=True)),
                ('string_es_es', models.TextField(blank=True)),
                ('string_es_mx', models.TextField(blank=True)),
                ('string_fr_ca', models.TextField(blank=True)),
                ('string_fr_fr', models.TextField(blank=True)),
                ('string_it_it', models.TextField(blank=True)),
                ('string_ja_jp', models.TextField(blank=True)),
                ('string_ko_kr', models.TextField(blank=True)),
                ('string_nl_nl', models.TextField(blank=True)),
                ('string_ru_ru', models.TextField(blank=True)),
                ('string_zh_cn', models.TextField(blank=True)),
                ('string_zh_tw', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameplateBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NameplateBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('HEAD', 'Head'), ('CLOTHING', 'Clothing'), ('SHOES', 'Shoes')],
                                          max_length=50)),
                ('rarity', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='splatnet_assets.brand')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                               to='splatnet_assets.image')),
                ('main_ability',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='splatnet_assets.ability')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                              to='splatnet_assets.localizationstring')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='brand',
                                       to='splatnet_assets.image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='splatnet_assets.localizationstring'),
        ),
        migrations.AddField(
            model_name='brand',
            name='unfavored_ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='splatnet_assets.ability'),
        ),
        migrations.AddField(
            model_name='ability',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.localizationstring'),
        ),
        migrations.AddField(
            model_name='ability',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
        ),
        migrations.AddField(
            model_name='ability',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='splatnet_assets.localizationstring'),
        ),
    ]
