# Generated by Django 4.2 on 2023-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='splatnet_assets/')),
                ('type', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=100)),
                ('original_file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
