# Generated by Django 4.2 on 2023-04-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('splatnet_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('splatnet_id', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'abilities'},
        ),
        migrations.AlterField(
            model_name='image',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='localizationstring',
            name='type',
            field=models.CharField(
                choices=[('OTHER', 'Other'), ('WEAPON_NAME', 'Weapon Name'), ('SUB_WEAPON_NAME', 'Sub Weapon Name'),
                         ('SPECIAL_WEAPON_NAME', 'Special Weapon Name'), ('TITLE_ADJECTIVE', 'Title Adjective'),
                         ('TITLE_SUBJECT', 'Title Subject'), ('HEAD_GEAR', 'Head Gear'),
                         ('CLOTHING_GEAR', 'Clothing Gear'), ('SHOES_GEAR', 'Shoes Gear'), ('ABILITY', 'Ability'),
                         ('ABILITY_DESCRIPTION', 'Ability Description'), ('BRAND', 'Brand'), ('STAGE', 'Stage')],
                max_length=50),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('splatnet_id', models.IntegerField()),
                ('flat_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                                    to='splatnet_assets.image')),
                ('image_3d', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                                  to='splatnet_assets.image')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                              to='splatnet_assets.localizationstring')),
                ('special',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='splatnet_assets.specialweapon')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='splatnet_assets.subweapon')),
            ],
        ),
        migrations.AddField(
            model_name='subweapon',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
        ),
        migrations.AddField(
            model_name='subweapon',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='splatnet_assets.localizationstring'),
        ),
        migrations.AddField(
            model_name='specialweapon',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
        ),
        migrations.AddField(
            model_name='specialweapon',
            name='mask_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
        ),
        migrations.AddField(
            model_name='specialweapon',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                       to='splatnet_assets.localizationstring'),
        ),
        migrations.AddField(
            model_name='specialweapon',
            name='overlay_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
        ),
    ]
