# Generated by Django 4.2 on 2023-04-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LocalizationString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('type', models.CharField(
                    choices=[('OTHER', 'Other'), ('WEAPON_NAME', 'Weapon Name'), ('SUB_WEAPON_NAME', 'Sub Weapon Name'),
                             ('SPECIAL_WEAPON_NAME', 'Special Weapon Name'), ('TITLE_ADJECTIVE', 'Title Adjective'),
                             ('TITLE_SUBJECT', 'Title Subject'), ('HEAD_GEAR', 'Head Gear'),
                             ('CLOTHING_GEAR', 'Clothing Gear'), ('SHOES_GEAR', 'Shoes Gear'), ('ABILITY', 'Ability'),
                             ('STAGE', 'Stage')], max_length=50)),
                ('string_de_de', models.TextField(blank=True)),
                ('string_en_gb', models.TextField(blank=True)),
                ('string_en_us', models.TextField(blank=True)),
                ('string_es_es', models.TextField(blank=True)),
                ('string_es_mx', models.TextField(blank=True)),
                ('string_fr_ca', models.TextField(blank=True)),
                ('string_fr_fr', models.TextField(blank=True)),
                ('string_it_it', models.TextField(blank=True)),
                ('string_ja_jp', models.TextField(blank=True)),
                ('string_ko_kr', models.TextField(blank=True)),
                ('string_nl_nl', models.TextField(blank=True)),
                ('string_ru_ru', models.TextField(blank=True)),
                ('string_zh_cn', models.TextField(blank=True)),
                ('string_zh_tw', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameplateBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NameplateBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
