# Generated by Django 4.2.2 on 2023-07-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizationstring',
            name='type',
            field=models.CharField(
                choices=[('OTHER', 'Other'), ('WEAPON_NAME', 'Weapon Name'), ('SUB_WEAPON_NAME', 'Sub Weapon Name'),
                         ('SPECIAL_WEAPON_NAME', 'Special Weapon Name'), ('TITLE_ADJECTIVE', 'Title Adjective'),
                         ('TITLE_SUBJECT', 'Title Subject'), ('HEAD_GEAR', 'Head Gear'),
                         ('CLOTHING_GEAR', 'Clothing Gear'), ('SHOES_GEAR', 'Shoes Gear'), ('ABILITY', 'Ability'),
                         ('ABILITY_DESCRIPTION', 'Ability Description'), ('BADGE_DESCRIPTION', 'Badge Description'),
                         ('AWARD', 'Award'), ('BRAND', 'Brand'), ('STAGE', 'Stage'),
                         ('CHALLENGE_NAME', 'Challenge Name'), ('CHALLENGE_DESCRIPTION', 'Challenge Description'),
                         ('CHALLENGE_LONG_DESCRIPTION', 'Challenge Long Description')], max_length=50),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                                     to='splatnet_assets.localizationstring')),
                ('long_description', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                                          to='splatnet_assets.localizationstring')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                              to='splatnet_assets.localizationstring')),
            ],
        ),
    ]
