# Generated by Django 4.2 on 2023-04-17 21:14

import django.db.models.deletion
from django.db import migrations, models

import splatnet_assets.fields


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0002_specialweapon_subweapon_alter_ability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameplatebackground',
            name='image',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameplatebackground',
            name='internal_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameplatebackground',
            name='splatnet_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameplatebackground',
            name='text_color',
            field=splatnet_assets.fields.ColorField(default=splatnet_assets.fields.Color(0, 0, 0, 0), max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameplatebadge',
            name='description',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT,
                                       to='splatnet_assets.localizationstring'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameplatebadge',
            name='image',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameplatebadge',
            name='internal_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameplatebadge',
            name='splatnet_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localizationstring',
            name='type',
            field=models.CharField(
                choices=[('OTHER', 'Other'), ('WEAPON_NAME', 'Weapon Name'), ('SUB_WEAPON_NAME', 'Sub Weapon Name'),
                         ('SPECIAL_WEAPON_NAME', 'Special Weapon Name'), ('TITLE_ADJECTIVE', 'Title Adjective'),
                         ('TITLE_SUBJECT', 'Title Subject'), ('HEAD_GEAR', 'Head Gear'),
                         ('CLOTHING_GEAR', 'Clothing Gear'), ('SHOES_GEAR', 'Shoes Gear'), ('ABILITY', 'Ability'),
                         ('ABILITY_DESCRIPTION', 'Ability Description'), ('BADGE_DESCRIPTION', 'Badge Description'),
                         ('BRAND', 'Brand'), ('STAGE', 'Stage')], max_length=50),
        ),
    ]
