# Generated by Django 4.2.7 on 2023-12-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0003_alter_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='splatnet_assets.image'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='image_banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='splatnet_assets.image'),
        ),
    ]
