# Generated by Django 4.2 on 2023-04-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0003_nameplatebackground_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='gold',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='internal_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='name',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT,
                                       to='splatnet_assets.localizationstring'),
            preserve_default=False,
        ),
    ]
