# Generated by Django 4.2.8 on 2024-02-15 02:19

from django.db import migrations, models
import splatnet_assets.fields


class Migration(migrations.Migration):

    dependencies = [
        ('splatnet_assets', '0004_alter_stage_image_alter_stage_image_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splatfest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('team_1_color', splatnet_assets.fields.ColorField(max_length=8)),
                ('team_2_color', splatnet_assets.fields.ColorField(max_length=8)),
                ('team_3_color', splatnet_assets.fields.ColorField(max_length=8)),
            ],
        ),
    ]
