# Generated by Django 4.2 on 2023-04-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0004_award_gold_award_internal_id_award_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizationstring',
            name='type',
            field=models.CharField(
                choices=[('OTHER', 'Other'), ('WEAPON_NAME', 'Weapon Name'), ('SUB_WEAPON_NAME', 'Sub Weapon Name'),
                         ('SPECIAL_WEAPON_NAME', 'Special Weapon Name'), ('TITLE_ADJECTIVE', 'Title Adjective'),
                         ('TITLE_SUBJECT', 'Title Subject'), ('HEAD_GEAR', 'Head Gear'),
                         ('CLOTHING_GEAR', 'Clothing Gear'), ('SHOES_GEAR', 'Shoes Gear'), ('ABILITY', 'Ability'),
                         ('ABILITY_DESCRIPTION', 'Ability Description'), ('BADGE_DESCRIPTION', 'Badge Description'),
                         ('AWARD', 'Award'), ('BRAND', 'Brand'), ('STAGE', 'Stage')], max_length=50),
        ),
        migrations.CreateModel(
            name='TitleSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('string', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                                to='splatnet_assets.localizationstring')),
            ],
        ),
        migrations.CreateModel(
            name='TitleAdjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=100)),
                ('string', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                                to='splatnet_assets.localizationstring')),
            ],
        ),
    ]
