# Generated by Django 5.0.2 on 2024-02-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splatnet_assets', '0005_splatfest'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='splatfest',
            index=models.Index(fields=['start_date', 'end_date'], name='splatnet_as_start_d_1005d8_idx'),
        ),
    ]
