# Generated by Django 4.2 on 2023-04-20 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0005_alter_localizationstring_type_titlesubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='image',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='image_banner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                       to='splatnet_assets.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='internal_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='name',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT,
                                       to='splatnet_assets.localizationstring'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='splatnet_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
