# Generated by Django 4.2 on 2023-04-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0006_stage_image_stage_image_banner_stage_internal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+',
                                    to='splatnet_assets.image'),
        ),
    ]
