# Generated by Django 5.0.2 on 2024-02-28 22:10

import django_choices_field.fields
import splatnet_assets.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='type',
            field=django_choices_field.fields.TextChoicesField(
                choices=[('HEAD', 'Head'), ('CLOTHING', 'Clothing'), ('SHOES', 'Shoes')],
                choices_enum=splatnet_assets.models.Gear.GearType, max_length=8),
        ),
        migrations.AlterField(
            model_name='localizationstring',
            name='type',
            field=django_choices_field.fields.TextChoicesField(
                choices=[('OTHER', 'Other'), ('WEAPON_NAME', 'Weapon Name'), ('SUB_WEAPON_NAME', 'Sub Weapon Name'),
                         ('SPECIAL_WEAPON_NAME', 'Special Weapon Name'), ('TITLE_ADJECTIVE', 'Title Adjective'),
                         ('TITLE_SUBJECT', 'Title Subject'), ('HEAD_GEAR', 'Head Gear'),
                         ('CLOTHING_GEAR', 'Clothing Gear'), ('SHOES_GEAR', 'Shoes Gear'), ('ABILITY', 'Ability'),
                         ('ABILITY_DESCRIPTION', 'Ability Description'), ('BADGE_DESCRIPTION', 'Badge Description'),
                         ('AWARD', 'Award'), ('BRAND', 'Brand'), ('STAGE', 'Stage'),
                         ('CHALLENGE_NAME', 'Challenge Name'), ('CHALLENGE_DESCRIPTION', 'Challenge Description'),
                         ('CHALLENGE_LONG_DESCRIPTION', 'Challenge Long Description')],
                choices_enum=splatnet_assets.models.LocalizationString.Type, max_length=26),
        ),
    ]
