# Generated by Django 5.0.2 on 2024-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splatnet_assets', '0006_splatfest_splatnet_as_start_d_1005d8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
