# Generated by Django 5.0.2 on 2024-03-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splatnet_assets', '0007_alter_gear_type_alter_localizationstring_type'),
        ('splatnet_assets', '0008_image_height_image_width'),
    ]

    operations = [
    ]
