# Generated by Django 4.2.1 on 2023-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battle',
            name='vs_mode',
            field=models.CharField(
                choices=[('REGULAR', 'Regular Battle'), ('LEAGUE', 'League Battle'), ('FEST', 'Splatfest Battle'),
                         ('BANKARA', 'Anarchy Battle'), ('X_MATCH', 'X Battle'), ('PRIVATE', 'Private Battle')],
                max_length=32),
        ),
    ]
