# Generated by Django 4.2 on 2023-04-12 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnprocessedBattle',
        ),
    ]
