# Generated by Django 4.2 on 2023-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0002_alter_battle_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='species',
            field=models.CharField(choices=[('INKLING', 'Inkling'), ('OCTOLING', 'Octoling')], default='INKLING',
                                   max_length=32),
            preserve_default=False,
        ),
    ]
