# Generated by Django 4.2.1 on 2023-06-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0001_initial'),
        ('battles', '0004_battle_splatfest_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='title_adjective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='splatnet_assets.titleadjective'),
        ),
        migrations.AlterField(
            model_name='player',
            name='title_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='splatnet_assets.titlesubject'),
        ),
    ]
