# Generated by Django 4.2 on 2023-04-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0004_alter_battle_judgement_alter_battle_knockout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='judgement',
            field=models.CharField(choices=[('WIN', 'Victory'), ('LOSE', 'Defeat'), ('DRAW', 'Draw'),
                                            ('EXEMPTED_LOSE', 'Defeat (Exempted)'), ('DEEMED_LOSE', 'Deemed Lose')],
                                   db_index=True, max_length=32),
        ),
    ]
