# Generated by Django 4.2 on 2023-04-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0005_alter_battle_judgement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['uploader', 'judgement'], name='battles_bat_uploade_275a8c_idx'),
        ),
    ]
