# Generated by Django 4.2.1 on 2023-06-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0005_alter_player_title_adjective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='x_battle_division',
            field=models.CharField(blank=True, choices=[('UNSPECIFIED', 'Unspecified'), ('TENTATEK', 'Tentatek'),
                                                        ('TAKOROKA', 'Takoroka')], max_length=32, null=True),
        ),
    ]
