# Generated by Django 4.2.1 on 2023-06-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0006_battle_x_battle_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='splatfest_power',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='x_battle_x_power',
        ),
        migrations.AddField(
            model_name='battle',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
