# Generated by Django 4.2.1 on 2023-05-04 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0006_battle_battles_bat_uploade_275a8c_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='player_clothing_gear',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_head_gear',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_name',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_name_id',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_nameplate_background',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_nameplate_badge_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_nameplate_badge_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_nameplate_badge_3',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_npln_id',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_paint',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_shoes_gear',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_title_adjective',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_title_subject',
        ),
    ]
