# Generated by Django 4.2.1 on 2023-06-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0007_remove_battle_splatfest_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='uploader_agent_extra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='battle',
            name='uploader_agent_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='battle',
            name='uploader_agent_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='battle',
            name='vs_mode',
            field=models.CharField(
                choices=[('REGULAR', 'Regular Battle'), ('CHALLENGE', 'Challenge'), ('FEST', 'Splatfest Battle'),
                         ('BANKARA', 'Anarchy Battle'), ('X_MATCH', 'X Battle'), ('PRIVATE', 'Private Battle')],
                max_length=32),
        ),
    ]
