# Generated by Django 4.2.1 on 2023-05-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0007_remove_battle_player_clothing_gear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='duration',
            field=models.DurationField(),
        ),
    ]
