# Generated by Django 4.2.1 on 2023-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0009_alter_battle_uploader_agent_extra_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['uploader', '-uploaded_at'], name='battles_bat_uploade_d3fc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['uploaded_at'], name='battles_bat_uploade_7668dd_idx'),
        ),
    ]
