# Generated by Django 4.2.2 on 2023-06-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0010_battle_battles_bat_uploade_d3fc8a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='judgement',
            field=models.CharField(blank=True, choices=[('WIN', 'Victory'), ('LOSE', 'Defeat'), ('DRAW', 'Draw')],
                                   max_length=32, null=True),
        ),
    ]
