# Generated by Django 4.2.2 on 2023-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0011_alter_team_judgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='splatfest_clout_contribution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='splatfest_festival_shells',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
