# Generated by Django 4.2.2 on 2023-06-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0012_battle_splatfest_clout_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='gpt_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='gpt_description_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='gpt_description_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
