# Generated by Django 4.2.2 on 2023-07-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0015_remove_battle_battles_bat_uploade_7668dd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fest_uniform_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
