# Generated by Django 4.2.2 on 2023-07-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('splatnet_assets', '0002_alter_localizationstring_type_challenge'),
        ('battles', '0016_alter_team_fest_uniform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='splatnet_assets.challenge'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='vs_rule',
            field=models.CharField(
                choices=[('TURF_WAR', 'Turf War'), ('TRI_COLOR', 'Tricolor Turf War'), ('AREA', 'Splat Zones'),
                         ('LOFT', 'Tower Control'), ('CLAM', 'Clam Blitz'), ('GOAL', 'Rainmaker')], max_length=32),
        ),
    ]
