# Generated by Django 4.2.2 on 2023-07-15 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0017_battle_challenge_alter_battle_vs_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='anarchy_points',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='battle',
            name='anarchy_rank',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='anarchy_s_plus_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0),
                                                                         django.core.validators.MaxValueValidator(50)]),
        ),
    ]
