# Generated by Django 4.2.3 on 2023-07-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0018_battle_anarchy_points_battle_anarchy_rank_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['-played_time'], name='battles_bat_played__a334b4_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['splatnet_id', 'id'], name='battles_bat_splatne_d1e327_idx'),
        ),
    ]
