# Generated by Django 5.0.2 on 2024-02-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0021_battlegroup'),
        ('splatnet_assets', '0006_splatfest_splatnet_as_start_d_1005d8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='splatfest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battles', to='splatnet_assets.splatfest'),
        ),
    ]
