# Generated by Django 5.0.2 on 2024-02-23 14:40

from django.db import migrations


def update_splatfests(apps, schema_editor):
    Battle = apps.get_model("battles", "Battle")
    Splatfest = apps.get_model("splatnet_assets", "Splatfest")
    for battle in Battle.objects.all():
        try:
            battle.splatfest = Splatfest.objects.filter(start_date__lte=battle.played_time,
                                                        end_date__gte=battle.played_time).first()
        except Splatfest.DoesNotExist:
            return None
        battle.save()


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0023_battle_splatfest'),
        ('splatnet_assets', '0005_splatfest')
    ]

    operations = [
        migrations.RunPython(update_splatfests),
    ]
