# Generated by Django 5.0.2 on 2024-02-28 22:59

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Battle = apps.get_model("battles", "Battle")
    Battle.objects.filter(vs_mode="LEAGUE").update(vs_mode="CHALLENGE")


class Migration(migrations.Migration):
    dependencies = [
        ('battles', '0025_alter_battle_anarchy_mode_alter_battle_judgement_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
