# Generated by Django 5.0.2 on 2024-03-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0022_alter_battle_anarchy_mode_alter_battle_judgement_and_more'),
        ('battles', '0024_auto_20240223_1440'),
        ('battles', '0026_rename_league'),
    ]

    operations = [
    ]
