# Generated by Django 5.0.3 on 2024-05-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0027_merge_20240302_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='splatnet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
