# Generated by Django 5.0.7 on 2024-07-14 01:19

import battles.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0029_battle_statink_id_battle_statink_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='splatfest_clout_multiplier',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('NONE', '1x'), ('DECUPLE', '10x'), ('DRAGON', '100x'), ('DOUBLE_DRAGON', '333x'), ('CONCH_SHELL_SCRAMBLE', 'Conch Clash'), ('CONCH_SHELL_SCRAMBLE_10', '10x Conch Clash'), ('CONCH_SHELL_SCRAMBLE_33', '33x Conch Clash')], choices_enum=battles.models.Battle.SplatfestBattleCloutMultiplier, max_length=23, null=True),
        ),
    ]
