# Generated by Django 5.0.6 on 2024-06-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splatnet_album', '0002_alter_albumimage_splatnet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='npln_image_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='splatnet_url',
            field=models.URLField(max_length=750, unique=True),
        ),
    ]
