# Generated by Django 4.2.3 on 2023-07-17 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_privacy_level_alter_group_pending_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pending_join_requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='pending_group_join_requests',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
