# Generated by Django 4.2.3 on 2023-07-17 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_group_pending_join_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='pending_invites',
            field=models.ManyToManyField(related_name='pending_group_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='pending_join_requests',
            field=models.ManyToManyField(related_name='pending_group_join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
