# Generated by Django 4.2.7 on 2023-11-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='initial_message',
            field=models.TextField(default=''),
        ),
    ]
