# Generated by Django 4.2.7 on 2023-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assistant', '0002_thread_initial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CREATED', 'Created')], max_length=25),
        ),
        migrations.AlterField(
            model_name='thread',
            name='openai_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
