# Generated by Django 4.2.7 on 2023-11-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assistant', '0003_thread_status_alter_thread_openai_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='runner_machine_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
