# Generated by Django 4.2.7 on 2023-11-30 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assistant', '0004_thread_runner_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='thread',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['content_type', 'object_id'], name='assistant_t_content_9f2484_idx'),
        ),
    ]
